# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-kubectl
  name: api-kubectl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-kubectl
  strategy: {}
  template:
    metadata:
      labels:
        app: api-kubectl
    spec:
      containers:
      - image: api-kubectl:v1
        name: api-kubectl
        resources: {}
status: {}
---
# Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-kubectl
  name: api-kubectl
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31412
  selector:
    app: api-kubectl
  type: NodePort
status:
  loadBalancer: {}