# Pod
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: api-kubectl
  name: api-kubectl
spec:
  containers:
  - env:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development
    image: api-kubectl:v1
    name: api-kubectl
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
# Service
apiVersion: v1
kind: Service
metadata:
  labels:
    run: api-kubectl
  name: api-kubectl
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31412
  selector:
    run: api-kubectl
  type: NodePort
status:
  loadBalancer: {}